name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Build Monorepo Site"]
  #   types:
  #     - completed

permissions:
  contents: read
  pages: write
  id-token: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        env:
          SHOW_ALL_USER: ${{ vars.SHOW_ALL_USER }}


  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      # Téléchargement des tous les artifacts précédents
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      # Upload d'un artefact unifié
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monorepo-site
          path: dist/
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
